export const eveningData = [
  {
    image: './images/evening/e1.jpg',
    title: 'Title1',
    index: 0,
    cName: 'content',
  },
  {
    image: './images/evening/e2.jpg',
    title: 'Title2',
    index: 1,
    cName: 'content',
  },
  {
    image: './images/evening/e3.jpg',
    title: 'Title3',
    index: 2,
    cName: 'content',
  },
  {
    image: './images/evening/e1.jpg',
    title: 'Title4',
    index: 3,
    cName: 'content',
  },
  {
    image: './images/evening/e2.jpg',
    title: 'Title5',
    index: 4,
    cName: 'content',
  },
  {
    image: './images/evening/e3.jpg',
    title: 'Title6',
    index: 5,
    cName: 'content ',
  },
  {
    image: './images/evening/e1.jpg',
    title: 'Title1',
    index: 6,
    cName: 'content ',
  },
  {
    image: './images/evening/e2.jpg',
    title: 'Title7',
    index: 7,
    cName: 'content ',
  },
  {
    image: './images/evening/e3.jpg',
    title: 'Title8',
    index: 8,
    cName: 'content ',
  },
  {
    image: './images/evening/e1.jpg',
    title: 'Title9',
    index: 9,
    cName: 'content ',
  },
  {
    image: './images/evening/e2.jpg',
    title: 'Title10',
    index: 10,
    cName: 'content ',
  },
  {
    image: './images/evening/e3.jpg',
    title: 'Title11',
    index: 11,
    cName: 'content ',
  },
  {
    image: './images/evening/e1.jpg',
    title: 'Title12',
    index: 12,
    cName: 'content ',
  },
  {
    image: './images/evening/e4.jpg',
    title: 'Title13',
    index: 13,
    cName: 'content ',
  },
  {
    image: './images/evening/e5.jpg',
    title: 'Title14',
    index: 14,
    cName: 'content ',
  },
  {
    image: './images/evening/e4.jpg',
    title: 'Title15',
    index: 15,
    cName: 'content ',
  },
  {
    image: './images/evening/e5.jpg',
    title: 'Title16',
    index: 16,
    cName: 'content ',
  },
  {
    image: './images/evening/e6.jpg',
    title: 'Title17',
    index: 17,
    cName: 'content ',
  },
  {
    image: './images/evening/e4.jpg',
    title: 'Title18',
    index: 18,
    cName: 'content ',
  },
  {
    image: './images/evening/e5.jpg',
    title: 'Title19',
    index: 19,
    cName: 'content ',
  },
  {
    image: './images/evening/e6.jpg',
    title: 'Title20',
    index: 20,
    cName: 'content ',
  },
  {
    image: './images/evening/e4.jpg',
    title: 'Title21',
    index: 21,
    cName: 'content ',
  },
  {
    image: './images/evening/e5.jpg',
    title: 'Title22',
    index: 22,
    cName: 'content ',
  },
  {
    image: './images/evening/e6.jpg',
    title: 'Title',
    index: 23,
    cName: 'content ',
  },
];

export const weddingData = [
  {
    image: './images/wedding/w1.jpg',
    title: 'Diamond Fox',
    index: 0,
    cName: 'content',
  },
  {
    image: './images/wedding/w2.jpg',
    title: 'August Ames',
    index: 1,
    cName: 'content',
  },
  {
    image: './images/wedding/w3.jpg',
    title: 'Zaczarowany Pierniczek',
    index: 2,
    cName: 'content',
  },
  {
    image: './images/wedding/w4.jpg',
    title: 'Ruchomy Kamień',
    index: 3,
    cName: 'content',
  },
  {
    image: './images/wedding/w5.jpg',
    title: 'Title5',
    index: 4,
    cName: 'content hidden ',
  },
  {
    image: './images/wedding/w6.jpg',
    title: 'Title6',
    index: 5,
    cName: 'content hidden ',
  },
];
